# This file was generated by GoReleaser. DO NOT EDIT.
cask "takt-ai" do
  version "0.0.14"

  on_macos do
    on_arm do
      sha256 "c255bccd4e895c88366917e874ee7e656c68e39d71db09c86ea8a50cc71f6a54"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "224a08ff799f4beb92cb254b4e9365da883b7549cb9735897c3e69f69d86503f"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "39bb654ed70522d7ab72a4355db00ad0afbb68245d439a5e76b5066f0852ce5d"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "25b880a510bf5e225a712700ace735c178147c755342a59617ae771c4a376241"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_linux_amd64.tar.gz"
    end
  end

  name "takt-ai"
  desc "Meta-harness for AI coding assistants."
  homepage "https://github.com/rou-cru/takt-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "takt-ai"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/takt-ai"]
    end
  end

  # No zap stanza required
end
