# This file was generated by GoReleaser. DO NOT EDIT.
cask "takt-ai" do
  version "0.0.18"

  on_macos do
    on_arm do
      sha256 "0eddebe9a5d00ccc3d785e8e9833a45dddcd9f25047ca6e13c0ee7dc6a9eadee"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d5fc4d379fc21abb7c7ebf4e24602acbd2dfbe2c5451886d21a89b6cc1d89000"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84e94769de353b47329c10d3e384ce3277a459d7c0534988cfea06bd7c38821f"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "37b7fc29d355fb1c464e83f70e69c80adfe6ccd04666f04d736cbd07254f6c3d"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_linux_amd64.tar.gz"
    end
  end

  name "takt-ai"
  desc "Meta-harness for AI coding assistants."
  homepage "https://github.com/rou-cru/takt-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "takt-ai"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/takt-ai"]
    end
  end

  # No zap stanza required
end
