# This file was generated by GoReleaser. DO NOT EDIT.
cask "takt-ai" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "2c677c0ba9a1d6e7ae050d154793db82ca40d15945714cd4e11545e49860fb73"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb8ccd708fc26c54497f4579e8d07ab0626e51337bb6d3512701a3d8db05f513"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0e4c3bb442627643f86f80695def903402d4be36a99483ddb14ca63d4784355f"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "659fcf6054f248b1d9935185fd95dfcadf014cf00cc4340f883939b4249257b1"
      url "https://github.com/rou-cru/takt-ai/releases/download/v#{version}/takt-ai_#{version}_linux_amd64.tar.gz"
    end
  end

  name "takt-ai"
  desc "Meta-harness for AI coding assistants."
  homepage "https://github.com/rou-cru/takt-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "takt-ai"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/takt-ai"]
    end
  end

  # No zap stanza required
end
